StoreMVC/Store/WebUI/Models/CartIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Store.Domain.Entities;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

StoreMVC/Store/WebUI/Models/GamesListViewModel.cs
using System.Collections.Generic;
using Store.Domain.Entities;

namespace Store.WebUI.Models
{
    public class GamesListViewModel
    {
        public IEnumerable<Game> Games { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentCategory { get; set; }
    }
}

StoreMVC/Store/WebUI/Models/MyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using Ninject.Infrastructure.Language;
using Store.Domain.Entities;

namespace WebUI.Models
{
    public class MyViewModel
    {
        public IEnumerable<A> MyColl
        {
            get
            {
            List<A> list = new List<A>();
            list.Add(new A
            {
                Id = 1, Name = "First A",
                BB = new List<B>()
                {
                   new B() { Id = 1, Name = "B1", CC = new List<C>()
                    {
                        new C() {Id = 1, Name  = "C1"},
                        new C() {Id = 2, Name  = "C2"}
                    }},
                    new B() { Id = 2, Name = "B2", CC = new List<C>()
                    {
                        new C() {Id = 3, Name  = "C3"},
                        new C() {Id = 4, Name  = "C4"}
                    }}
                }
                }
            );
                list.Add(new A
                {
                    Id = 2,
                    Name = "Second A",
                    BB = new List<B>()
                {
                   new B() { Id = 3, Name = "B3", CC = new List<C>()
                    {
                        new C() {Id = 5, Name  = "C5"},
                        new C() {Id = 6, Name  = "C6"}
                    }},
                    new B() { Id = 4, Name = "B4", CC = new List<C>()
                    {
                        new C() {Id = 7, Name  = "C7"},
                        new C() {Id = 8, Name  = "C8"}
                    }}
                }
                }
            );
                return list;

            return new List<A>(); 
                
            }
            set { }
        }


        public IEnumerable<B> GetB { get; set; }

        public IEnumerable<B> GetBB(int Id)
        {
            return MyColl.Where(a=>a.Id==Id).Select(r=>r.BB).FirstOrDefault();
        }
    }
}

StoreMVC/Store/WebUI/Models/PageInfo.cs
using System;

namespace Store.WebUI.Models
{
    public class PagingInfo
    {
        // Кол-во товаров
        public int TotalItems { get; set; }

        // Кол-во товаров на одной странице
        public int ItemsPerPage { get; set; }

        // Номер текущей страницы
        public int CurrentPage { get; set; }

        // Общее кол-во страниц
        public int TotalPages
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

StoreMVC/Store/WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using Store.Domain.Entities;
using Store.Domain.Abstract;
using Store.WebUI.Models;
using WebUI.Models;

namespace Store.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IGameRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IGameRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                cart.AddItem(game, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int gameId, string returnUrl)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                cart.RemoveLine(game);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

StoreMVC/Store/WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Store.Domain.Abstract;
using Store.Domain.Entities;
using Store.WebUI.Models;
using WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        private IGameRepository repository;
        public int pageSize = 4;

        public GameController(IGameRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            MyViewModel model = new MyViewModel();
            return View(model);
        }
        public ViewResult GoToB(int Id)
        {
            MyViewModel model = new MyViewModel();
            model.GetB = model.GetBB(Id);
                       
            return View("MyPartial", model);
        }//()

        public ViewResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = repository.Games
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.GameId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                repository.Games.Count() :
                repository.Games.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            ViewBag.ForPartial = "For partial";
            return View(model);
        }
    }
}

StoreMVC/Store/WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Store.Domain.Abstract;

namespace Store.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IGameRepository repository;

        public NavController(IGameRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Games
                .Select(game => game.Category)
                .Distinct()
                .OrderBy(x => x);

            return PartialView("FlexMenu", categories);
        }

    }
}

StoreMVC/Store/WebUI/Views/Cart/Checkout.cshtml
@model Store.Domain.Entities.ShippingDetails

@{
    ViewBag.Title = "Store: форма заказа";
}

<h2>Оформить заказ сейчас</h2>
<p>Пожалуйста введи ваши контактные данные, и мы сразу отправим товар!</p>


@using (Html.BeginForm())
{   
    @Html.ValidationSummary()//Отображение ошибок ввода
    <h3>Данные</h3>
    <div class="form-group">
        <label>Ваше имя:</label>
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>

    <h3>Адрес доставки</h3>
    <div class="form-group">
        <label>Первый адрес:</label>
        @Html.TextBoxFor(x => x.Line1, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Второй адрес:</label>
        @Html.TextBoxFor(x => x.Line2, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Третий адрес:</label>
        @Html.TextBoxFor(x => x.Line3, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Город:</label>
        @Html.TextBoxFor(x => x.City, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Страна:</label>
        @Html.TextBoxFor(x => x.Country, new { @class = "form-control" })
    </div>

    <h3>Опции</h3>
    <div class="checkbox">
        <label>
            @Html.EditorFor(x => x.GiftWrap)
            Использовать подарочную упаковку?
        </label>
    </div>

    <div class="text-center">
        <input class="btn btn-primary" type="submit" value="Обработать заказ" />
    </div>
}

StoreMVC/Store/WebUI/Views/Cart/Completed.cshtml
@{
    ViewBag.Title = "Заказ обработан";
}

<h2>Спасибо!</h2>
<p>Спасибо за выбор нашего магазина. Заказ в кратчайшие сроки будет отправлен в службу доставки.</p>

StoreMVC/Store/WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "GameStore: ваша корзина";
}

<h2>Ваша корзина</h2>
<table class="table">
    <thead>
        <tr>
            <th>Кол-во</th>
            <th>Игра</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Общая цена</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Game.Name</td>
                <td class="text-right">@line.Game.Price.ToString("# руб")</td>
                <td class="text-right">
                    @((line.Quantity * line.Game.Price).ToString("# руб"))
                </td>
                <td>
                    @using (Html.BeginForm("RemoveFromCart", "Cart"))
                    {
                        @Html.Hidden("GameId", line.Game.GameId)
                        @Html.HiddenFor(x => x.ReturnUrl)
                        <input class="btn btn-sm btn-warning" type="submit" value="Удалить" />
                    }
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
    @Html.ActionLink("Оформить заказ", "Checkout", null, new { @class = "btn btn-primary" })
</div>

StoreMVC/Store/WebUI/Views/Cart/Summary.cshtml
@model Store.Domain.Entities.Cart

<div class="navbar-right hidden-xs">
    @Html.ActionLink("Заказать", "Index", "Cart",
    new { returnUrl = Request.Url.PathAndQuery },
    new { @class = "btn btn-default navbar-btn" })
</div>

<div class="navbar-right visible-xs">
    <a href=@Url.Action("Index", "Cart", new { returnUrl = Request.Url.PathAndQuery })
       class="btn btn-default navbar-btn">
        <span class="glyphicon glyphicon-shopping-cart"></span>
    </a>
</div>

<div class="navbar-text navbar-right">
    <b class="hidden-xs">Ваша корзина:</b>
    @Model.Lines.Sum(x => x.Quantity) игр,
    @Model.ComputeTotalValue().ToString("# руб")
</div>

StoreMVC/Store/WebUI/Views/Game/Index.cshtml
@model WebUI.Models.MyViewModel
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>Go to B</th>
        </tr>
        @foreach (var link in @Model.MyColl)
        {
            <tr>
                <td>@link.Id</td>
                <td>@link.Name</td>
                <td>
                    @Html.DropDownListFor(
                    model => @link.BB,
                    @link.BB.Select(h => new SelectListItem
                    {
                        Text = $"{ h.Name} Depatment {h.Id}",
                            Value = h.Id.ToString()
                        }),
                    "Please select a B");
            </td>
                <td>@Html.ActionLink("Go to B", "GoToB", "Game", new {Id = @link.Id}, null) </td>
                
            </tr>
        }
</table>

StoreMVC/Store/WebUI/Views/Game/List.cshtml
@using Store.WebUI.Models
@using Store.WebUI.HtmlHelpers
@model GamesListViewModel

@{
    ViewBag.Title = "Товары";
}
@Html.Partial("MyPartial")

@foreach (var p in @Model.Games)
{
    @Html.Partial("GameSummary", p)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List",
        new {page = x, category = Model.CurrentCategory}))
</div>

<div class="btn btn-group pull-right">
    
</div>

StoreMVC/Store/WebUI/Views/Nav/FlexMenu.cshtml
@model IEnumerable<string>

@{
    bool horizontal = ((bool)(ViewContext.RouteData.Values["horizontalNav"] ?? false));
    string wrapperClasses = horizontal ? "btn-group btn-group-sm btn-group-justified" : null;
}

<div class="@wrapperClasses">

    @Html.ActionLink("Домой", "List", "Game", null,
    new
    {
        @class = horizontal ? "btn btn-default btn-sm" :
            "btn btn-block btn-default btn-lg"
    })

    @foreach (var link in Model)
    {
        @Html.RouteLink(link, new
   {
       controller = "Game",
       action = "List",
       category = link,
       page = 1
   }, new
   {
       @class = (horizontal ? "btn btn-default btn-sm"
                : "btn btn-block btn-default btn-lg")
                + (link == ViewBag.SelectedCategory ? " btn-primary" : "")
   })
    }

</div>

StoreMVC/Store/WebUI/Views/Shared/GameSummary.cshtml
@model Store.Domain.Entities.Game

<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# руб")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.GameId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Добавить в корзину" />
        </div>
    }
    <span class="lead">@Model.Description</span>
</div>

StoreMVC/Store/WebUI/Views/Shared/MyPartial.cshtml
@model WebUI.Models.MyViewModel
<table class="table table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>NAME</th>
        </tr>
        @foreach (var link in @Model.GetB)
        {
            <tr>
                <td>@link.Id</td>
                <td>@link.Name</td>
            </tr>
        }
</table>

StoreMVC/Store/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
    <style>
        .navbar-right {
            float: right !important;
            margin-right: 15px;
            margin-left: 15px;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">
            <span class="hidden-xs">GameStore - магазин компьютерных игр</span>
            <div class="visible-xs">Game</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>

    <div class="visible-xs">
        @Html.Action("Menu", "Nav", new { horizontalNav = true })
    </div>

    <div class="row panel">
        <div id="categories" class="col-sm-3 hidden-xs">
            @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-12 col-sm-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>